version: "3.9"
services:
  mariadb:
    image: mariadb:10.4
    container_name: osoc-dev
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=osoc_dev
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  data:
