"""refactor and add ProjectRoleSuggestion

Revision ID: 2403b70be336
Revises: d4eaf2b564a4
Create Date: 2022-04-24 22:40:57.961685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2403b70be336'
down_revision = 'd4eaf2b564a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('set FOREIGN_KEY_CHECKS=0')

    with op.batch_alter_table('project_roles', schema=None) as batch_op:
        batch_op.drop_constraint('PRIMARY', type_='primary')
        #batch_op.add_column(sa.Column('project_role_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slots', sa.Integer(), nullable=False))
        #batch_op.drop_constraint('project_roles_students_fk', type_='foreignkey')
        #batch_op.drop_constraint('project_roles_users_fk', type_='foreignkey')
        batch_op.drop_column('definitive')
        batch_op.drop_column('student_id')
        batch_op.drop_column('argumentation')
        batch_op.drop_column('drafter_id')

    #op.create_primary_key('PRIMARY', 'project_roles', ['project_role_id'])
    op.execute("ALTER TABLE project_roles ADD project_role_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT;")

    op.create_table(
        'pr_suggestions',
        sa.Column('project_role_suggestion_id', sa.Integer(), nullable=False),
        sa.Column('argumentation', sa.Text(), nullable=True),
        sa.Column('project_role_id', sa.Integer(), nullable=True),
        sa.Column('student_id', sa.Integer(), nullable=True),
        sa.Column('drafter_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['drafter_id'], ['users.user_id'], name='pr_suggestions_users_fk'),
        sa.ForeignKeyConstraint(['project_role_id'], ['project_roles.project_role_id'], name='pr_suggestions_project_roles_fk'),
        sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='pr_suggestions_students_fk'),
        sa.PrimaryKeyConstraint('project_role_suggestion_id')
    )

    op.drop_table('project_skills')

    with op.batch_alter_table('decision_emails', schema=None) as batch_op:
        batch_op.alter_column(
            'decision',
            existing_type=mysql.ENUM(
                'APPLIED', 'AWAITING_PROJECT', 'APPROVED', 'CONTRACT_CONFIRMED',
                'CONTRACT_DECLINED', 'REJECTED', collation='utf8mb4_unicode_ci'
            ),
            nullable=False
        )

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('number_of_students')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column(
            'coach_id',
            existing_type=mysql.INTEGER(display_width=11),
            nullable=True
        )
        batch_op.drop_index('unique_coach_student_suggestion')

    op.execute('set FOREIGN_KEY_CHECKS=1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('set FOREIGN_KEY_CHECKS=0')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index('unique_coach_student_suggestion', ['coach_id', 'student_id'], unique=False)
        batch_op.alter_column(
            'coach_id',
            existing_type=mysql.INTEGER(display_width=11),
            nullable=False
        )

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('number_of_students', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    with op.batch_alter_table('project_roles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('drafter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)
        )
        batch_op.add_column(sa.Column('argumentation', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(
            sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column('definitive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key('project_roles_students_fk', 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key('project_roles_users_fk', 'users', ['drafter_id'], ['user_id'])
        batch_op.drop_column('slots')
        batch_op.drop_column('description')
        batch_op.drop_column('project_role_id')

    with op.batch_alter_table('decision_emails', schema=None) as batch_op:
        batch_op.alter_column('decision',
                              existing_type=mysql.ENUM('APPLIED', 'AWAITING_PROJECT', 'APPROVED', 'CONTRACT_CONFIRMED',
                                                       'CONTRACT_DECLINED', 'REJECTED', collation='utf8mb4_unicode_ci'),
                              nullable=True)

    op.create_table('project_skills',
                    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('skill_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='project_skills_projects_fk'),
                    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], name='project_skills_skills_fk'),
                    mariadb_collate='utf8mb4_unicode_ci',
                    mariadb_default_charset='utf8mb4',
                    mariadb_engine='InnoDB'
                    )
    op.drop_table('pr_suggestions')

    op.execute('set FOREIGN_KEY_CHECKS=1')
    # ### end Alembic commands ###
