"""added to the right side of the relationship this time

Revision ID: 32e41fa0af0a
Revises: 54119dfdbb44
Create Date: 2022-04-10 15:15:05.204273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e41fa0af0a'
down_revision = '54119dfdbb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
