"""Create enum for email statuses

Revision ID: 43e6e98fe039
Revises: a4a047b881db
Create Date: 2022-04-13 16:24:26.687617

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43e6e98fe039'
down_revision = 'a4a047b881db'
branch_labels = None
depends_on = None

new_type = sa.Enum('APPLIED', 'AWAITING_PROJECT', 'APPROVED', 'CONTRACT_CONFIRMED', 'CONTRACT_DECLINED', 'REJECTED',
                   name='emailstatusenum')
old_type = sa.Enum('UNDECIDED', 'YES', 'MAYBE', 'NO', name='decisionenum')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decision_emails", schema=None) as batch_op:
        batch_op.alter_column("decision", type_=new_type, existing_type=old_type)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decision_emails", schema=None) as batch_op:
        batch_op.alter_column("decision", type_=old_type, existing_type=new_type)
    # ### end Alembic commands ###
