"""added cascade delete

Revision ID: 54119dfdbb44
Revises: 1862d7dea4cc
Create Date: 2022-04-10 15:10:51.251243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54119dfdbb44'
down_revision = '1862d7dea4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
