"""add admin field, remove userrole table, link user to edition

Revision ID: 73e669bda33d
Revises: 145816a4b2df
Create Date: 2022-03-12 22:01:41.966008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73e669bda33d'
down_revision = '145816a4b2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_editions',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('edition_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['edition_id'], ['editions.edition_id'], 'user_editions_editions_fk'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], 'user_editions_users_fk')
    )
    op.drop_table('user_roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    op.create_table(
        'user_roles',
        sa.Column('user_role_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.Column('role', mysql.ENUM('ADMIN', 'COACH'), nullable=True),
        sa.Column('edition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['edition_id'], ['editions.edition_id'], name='user_roles_editions_fk'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_roles_users_fk'),
        sa.PrimaryKeyConstraint('user_role_id'),
        mariadb_default_charset='latin1',
        mariadb_engine='InnoDB'
    )
    op.drop_table('user_editions')
    # ### end Alembic commands ###
