"""multiple column unique constraint coach & student suggestion

Revision ID: 8c97ecc58e5f
Revises: f125e90b2cf3
Create Date: 2022-03-16 21:07:44.193388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c97ecc58e5f'
down_revision = 'f125e90b2cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_coach_student_suggestion', ['coach_id', 'student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_coach_student_suggestion', type_='unique')

    # ### end Alembic commands ###
