"""student has cascade on delete

Revision ID: 94f24b41f33e
Revises: 1862d7dea4cc
Create Date: 2022-04-17 17:41:40.174255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f24b41f33e'
down_revision = '1862d7dea4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_emails', schema=None) as batch_op:
        batch_op.drop_constraint('decision_emails_students_fk', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('decision_emails_students_fk', 'students', ['student_id'], ['student_id'])

    # ### end Alembic commands ###
