"""add name to edition

Revision ID: a5f19eb19cca
Revises: ca4c4182b93a
Create Date: 2022-03-27 14:16:49.714952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f19eb19cca'
down_revision = 'ca4c4182b93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.create_unique_constraint("uq_edition_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.drop_constraint("uq_edition_name", type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
