"""Link invitation links to editions

Revision ID: c06da164d5b9
Revises: 6433759fff33
Create Date: 2022-03-05 18:21:11.833535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06da164d5b9'
down_revision = '6433759fff33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('edition_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_invite_links_editions_edition", 'invite_links', 'editions', ['edition_id'], ['edition_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_invite_links_editions_edition", 'invite_links', type_='foreignkey')
    op.drop_column('invite_links', 'edition_id')
    # ### end Alembic commands ###
