"""moved email to AuthEmail

Revision ID: ca4c4182b93a
Revises: f125e90b2cf3
Create Date: 2022-03-27 10:47:50.051982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca4c4182b93a'
down_revision = 'f125e90b2cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_auths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=False))
        batch_op.create_unique_constraint("uq_email_auth_email", ['email'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('email_auths', schema=None) as batch_op:
        batch_op.drop_constraint("uq_email_auth_email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
