"""Remove leftover refactored association tables

Revision ID: d29dfe421181
Revises: b6a373574e13
Create Date: 2022-03-05 22:43:56.712372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29dfe421181'
down_revision = 'b6a373574e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
