name: Backend CI
on:
  pull_request:
  push:
    branches:
      - master
      - develop

defaults:
  run:
    working-directory: backend

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /usr/local/lib/python3.10/site-packages
          key: venv-${{ runner.os }}-bullseye-3.10.2-v2-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-bullseye-3.10.2-v2

      - if: steps.cache.outputs.cache-hit != 'true'
        run: apt update

      - if: steps.cache.outputs.cache-hit != 'true'
        run: apt install -y build-essential libmariadb-dev

      - if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -U pip poetry

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m poetry export --dev --format requirements.txt --output requirements.txt --without-hashes
          pip install -r requirements.txt

  Test:
    needs: [Dependencies]
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /usr/local/lib/python3.10/site-packages
          key: venv-${{ runner.os }}-bullseye-3.10.2-v2-${{ hashFiles('**/poetry.lock') }}

      - run: python -m pytest --cov=src --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2

  Lint:
    needs: [Test]
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /usr/local/lib/python3.10/site-packages
          key: venv-${{ runner.os }}-bullseye-3.10.2-v2-${{ hashFiles('**/poetry.lock') }}

      - run: python -m pylint src

  Type:
    needs: [Test]
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /usr/local/lib/python3.10/site-packages
          key: venv-${{ runner.os }}-bullseye-3.10.2-v2-${{ hashFiles('**/poetry.lock') }}

      - run: python -m mypy src
