name: Backend CI
on: [push]

defaults:
  run:
    working-directory: backend

jobs:
  Test:
    runs-on: self-hosted
    container: python:3.10.2-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: python -m pytest