name: Backend CI
on: [push]

defaults:
  run:
    working-directory: backend

jobs:
  dependencies:
    runs-on: self-hosted
    container: python:3.10.2-alpine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: venv
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: apk add gcc musl-dev build-base

      - if: steps.cache.outputs.cache-hit != 'true'
        run: python -m venv venv && . venv/bin/activate

      - if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements-dev.txt

  Test:
    needs: [dependecies]
    runs-on: self-hosted
    container: python:3.10.2-alpine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

      - run: python -m pytest

