name: Frontend CI
on:
  pull_request:
  push:
    branches:
      - master
      - develop

defaults:
  run:
    working-directory: frontend

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    container: node:16.14.0-bullseye-slim
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache

      - if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline

  Test:
    needs: [Dependencies]
    runs-on: ubuntu-latest
    container: node:16.14.0-bullseye-slim
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - run: yarn install --prefer-offline
      - run: yarn test

  Lint:
    needs: [Test]
    runs-on: ubuntu-latest
    container: node:16.14.0-bullseye-slim
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - run: yarn install --prefer-offline
      - run: yarn run lint

  Style:
    needs: [Test]
    runs-on: ubuntu-latest
    container: node:16.14.0-bullseye-slim
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - run: yarn install --prefer-offline
      - run: yarn run prettier -c src

  Build:
    needs: [Style, Lint]
    runs-on: ubuntu-latest
    container: node:16.14.0-bullseye-slim
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - run: yarn install --prefer-offline
      - run: yarn build
